
import "./globals.css";
import Navbar from "./COMPONENTS/NAVBAR/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import {UserContextProvider} from "./context/userContext"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body >
        <UserContextProvider>
          <Navbar />
          <main>
            {children}
          </main>
        </UserContextProvider>
      </body>
    </html>
  );
}
